NAME
.TH tz-converter 1 2014-08-05
.SH NAME
tz-converter \- convert the time and date across time zones.
.SH SYNOPSIS
.B tz-converter
[
.BI - options
]
.SH DESCRIPTION
.B tz-converter
is a simple interface for converting the time and date between two time zones. Written in Python3 and using Pyside, this interface allows the user to save a certain time zone and restore it after further changes. The timezone information is taken from pytz, supplying seven different regions: Africa, America, Asia, Australia, Europe, Pacific, and US.
.SH OPTIONS
This program currently has no documented commandline options.
.SH COPYRIGHT
Copyright  ©  2014 by David Maiorino. This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
.SH AUTHOR
David Maiorino.
